"""Add is_completed column to Playlist

Revision ID: 62224d5223db
Revises: 7934a936c43f
Create Date: 2024-12-10 20:36:25.031584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62224d5223db'
down_revision: Union[str, None] = '7934a936c43f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlist', sa.Column('is_completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playlist', 'is_completed')
    # ### end Alembic commands ###
