"""remove photo_url column

Revision ID: ec21acbad484
Revises: 5219e3fd55e7
Create Date: 2024-12-10 17:48:30.594745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec21acbad484'
down_revision: Union[str, None] = '5219e3fd55e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlist', sa.Column('photo_url', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('playlist', 'photo_url')
    # ### end Alembic commands ###
